### PR TITLE
Updates README.rst with svg badge

### PR DESCRIPTION
**Pull request by sobolevn**

### CODE REVIEW

**Comment by sobolevn** [comment]
I use a bot written in `elixir` actually. It does pretty much the same:
1. Finding bad icons
2. Replaces it with `svg` ones
 
And sends pull requests as it was me. I am going to open-source it as soon as possible.

**Comment by mgedmin** [comment]
I'm not sure we want to deal with 60+ pull requests.

I've a directory with all of zopefoundation repos checked out.  I can run a few shell one-liners and commit + push the change to all of them.  (I've done a few updates like this before, e.g. to upgrade the included copy of `bootstrap.py`.)

What I don't have is the energy to come up with the correct shell one-liner to run today.  ;)

**Comment by sobolevn** [comment]
`sed` all the things! Thanks for the quick reaction!

**Comment by mgedmin** [comment]
```
cd ~/src/zopefoundation
ghcloneall 
grep -l https://travis-ci.org/.*.png */README.rst|cut -d/ -f1 > PACKAGES
wc -l PACKAGES  # => 73
grep -l https://travis-ci.org/.*.png */README.rst|xargs sed -i '/https:\/\/travis-ci.org\//s/[.]png/.svg/'
for p in $(cat PACKAGES); do (cd $p && echo + $p && git diff); done  # whoops zc.zodbwsgi is special
(cd zc.zodbwsgi && git checkout .)
grep -l https://travis-ci.org/.*.png */README.rst|xargs sed -i '/https:\/\/travis-ci.org\//s/[.]png/.svg/' --follow-symlinks
for p in $(cat PACKAGES); do (cd $p && echo + $p && git diff); done  # all ok
for p in $(cat PACKAGES); do (cd $p && git commit -am "Use SVG icon for Travis" && git push); done
```

**Pull request merged**
