### PR TITLE
chore: prep 7.0.1 release

### PR DESCRIPTION
**Pull request by tseaver**

### CODE REVIEW

**Review by dataflake — APPROVED** [review]

**Comment by dataflake** [comment]
You create and push the tag, which will build all binary packages. You yourself create the tarball and upload it. I always do `bin/buildout setup setup.py sdist` followed by `bin/twine upload dist/XXX.tar.gz` (I always have `twine` right in my virtual environment)

**Comment by dataflake** [comment]
And yes, an svb commit to cap it all off

**Comment by tseaver** [comment]
/me wonders why we don't have the GHA workflow push the `sdist` as well.

**Comment by dataflake** [comment]
No idea, I didn't have the will to look into it yet and haven't been bothered too much.

**Comment by tseaver** [comment]
@dataflake I was thinking about the new PyPI rules about tokens (they can't be scope to organizations, only projects, or else all projects).

**Comment by tseaver** [comment]
Also, I almost uploaded a `zope_interface-7.0.1.tar.gz` a moment ago, as I forgot that we have to build with a pinned `setuptools`.

**Comment by dataflake** [comment]
I have a command line expansion that sets up virtual environments with all those (stupid) pins in place so I hardly ever see that issue.

**Pull request merged**
