### PR TITLE
CI for travis and appveyor

### PR DESCRIPTION
**Pull request by fgregg**
Applying what we @mgedmin, @tseaver and I learned in https://github.com/zopefoundation/BTrees/

@mgedmin I think you will need to reencrypt the zope.wheelbuilder password for travis.

### CODE REVIEW

**Comment by fgregg** [comment]
@mgedmin if you'll generate a new secure pypipassword, this would be ready to merge.

**Comment by mgedmin** [comment]
```
  secure: "Ra1KZO3VAF+1gEZgXiAMYIH+nfJ7J7tUZ7x+FFhHO2Gw3y6wvhpdnV0Tb3U6ZtWQh6ouvcGlCFHMeygoQ2j8WvTyo4l10qSfQVnjoNg2c/z294o9tv2WyRhZzyGvs587BxolBG+eqBuO6JUSIVl4uiPAORBcV1TdrErhjgdHiLk="
```

**Comment by mgedmin** [comment]
@fgregg you're a hero!

**Comment by fgregg** [comment]
This should be ready.

**Comment by tseaver** [comment]
Thank you!

**Comment by tseaver** [comment]
@fgregg The `osx` builds on Travis don't seem to have uploaded wheels for the 4.2.0 release:

- https://travis-ci.org/zopefoundation/zope.interface/jobs/136706850
- https://travis-ci.org/zopefoundation/zope.interface/jobs/136706851
- https://travis-ci.org/zopefoundation/zope.interface/jobs/136706852

**Comment by fgregg** [comment]
Oops. You need to add zope.wheelbuilder as a pypi maintainer

**Comment by tseaver** [comment]
Done.  Can we just re-run those jobs, then?

**Comment by tseaver** [comment]
> Can we just re-run those jobs, then?

(Assuming so, I've restarted them).

**Comment by fgregg** [comment]
yes

**Comment by tseaver** [comment]
OK, that worked for Macs.  The zope.winbot built eggs/MSIs for 2.6, 2.7, and 3.2, but I don't see appveyor-built wheels (maybe they're just slow?)

**Comment by fgregg** [comment]
Appveyor is much slower. I'm pretty sure they will work.

**Comment by tseaver** [comment]
Yup:  Windows wheels are there now.

**Pull request merged**
