### PR TITLE
Preliminary support for Python 3.14a2.

### LINKED ISSUE #334: Test failure with Python 3.14
When testing the latest version of zope.interface with the latest available Python 3.14 alpha, the test failed with the following error:

```
python3 -m unittest discover -vv -s zope/interface -t .
zope.interface (unittest.loader._FailedTest.zope.interface) ... ERROR

======================================================================
ERROR: zope.interface (unittest.loader._FailedTest.zope.interface)
----------------------------------------------------------------------
ImportError: Failed to import test module: zope.interface
Traceback (most recent call last):
  File "/usr/lib64/python3.14/unittest/loader.py", line 429, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib64/python3.14/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
    ~~~~~~~~~~^^^^^^
  File "/builddir/build/BUILD/python-zope-interface-7.1.1-build/BUILDROOT/usr/lib64/python3.14/site-packages/zope/interface/__init__.py", line 58, in <module>
    _wire()
    ~~~~~^^
  File "/builddir/build/BUILD/python-zope-interface-7.1.1-build/BUILDROOT/usr/lib64/python3.14/site-packages/zope/interface/interface.py", line 1154, in _wire
    from zope.interface.interfaces import IElement
  File "/builddir/build/BUILD/python-zope-interface-7.1.1-build/BUILDROOT/usr/lib64/python3.14/site-packages/zope/interface/interfaces.py", line 56, in <module>
    class IElement(Interface):
    ...<93 lines>...
            """
  File "/builddir/build/BUILD/python-zope-interface-7.1.1-build/BUILDROOT/usr/lib64/python3.14/site-packages/zope/interface/interface.py", line 794, in __init__
    self.__attrs = self.__compute_attrs(attrs)
                   ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/builddir/build/BUILD/python-zope-interface-7.1.1-build/BUILDROOT/usr/lib64/python3.14/site-packages/zope/interface/interface.py", line 813, in __compute_attrs
    aname: update_value(aname, aval)
           ~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/builddir/build/BUILD/python-zope-interface-7.1.1-build/BUILDROOT/usr/lib64/python3.14/site-packages/zope/interface/interface.py", line 809, in update_value
    raise InvalidInterface("Concrete attribute, " + aname)
zope.interface.exceptions.InvalidInterface: Concrete attribute, __classdictcell__


----------------------------------------------------------------------
Ran 1 test in 0.000s
```

I've tried to look at the `__classdictcell__` attribute but it seems it's not new in 3.14.

### PR DESCRIPTION
**Pull request by icemac**
I hacked something together so the tests do not fail for Python 3.14.
But I am completly unsure if this is the way we want/should go.

Fixes #334.

### CODE REVIEW

**Comment by dataflake** [comment]
I can see the fix for that missing `__classdictcell__` slot, but what's the `IByteString` change for?

Also, if you only want to test "is this Python 3.14", why do you need all those definitions for the older versions?

**Review by d-maurer — COMMENTED** [review]
Why do you remove the `IByteString` definitions (in `common.builtins` and `common.collections`) for Python 3.14? The interface is likely useful for that version as well.

**Comment by icemac** [comment]
> I can see the fix for that missing `__classdictcell__` slot, but what's the `IByteString` change for?

Python 3.14 removed `collections.abc.ByteString`, see https://docs.python.org/3/library/collections.abc.html#collections.abc.ByteString

> Also, if you only want to test "is this Python 3.14", why do you need all those definitions for the older versions?

`ByteString` can only be used in Python < 3.14, using this long list of versions supporting it, we'll see that we can remove it when we remove Python 3.13 support in a couple of years. But you are right, this can be done easier but still greppable.

**Comment by icemac** [comment]
> Why do you remove the `IByteString` definitions (in `common.builtins` and `common.collections`) for Python 3.14? The interface is likely useful for that version as well.

@d-maurer 
I did not see an obvious way to keep it after Python 3.14 removed `collections.abs.ByteString`, see [ByteString](https://docs.python.org/3/library/collections.abc.html#collections.abc.ByteString) – maybe you find one.

**Comment by dataflake** [comment]
I have applied a suggestion for a simpler version check in https://github.com/zopefoundation/zope.interface/pull/335/commits/1f6009f86af7b05a4f7f24cf50e1e46b6aae3283 - feel free to revert if you don't agree.

I am not sure what to do about the ByteString issue because I don't know if or how widespread the use of that interface is.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2024-11-26 23:56 -0800:
>> Why do you remove the `IByteString` definitions (in `common.builtins` and `common.collections`) for Python 3.14? The interface is likely useful for that version as well.
>
>@d-maurer
>I did not see an obvious way to keep it after Python 3.14 removed `collections.abs.ByteString`, see [ByteString](https://docs.python.org/3/library/collections.abc.html#collections.abc.ByteString) – maybe you find one.

Convinced! I was unaware of this change in Python 3.14.

**Review by dataflake — APPROVED** [review]

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
