### PR TITLE
Update to the latest c-code template

### PR DESCRIPTION
**Pull request by mgedmin**
Add a regression test for CFLAGS not having -Ofast, which is known to break things.  See https://github.com/zopefoundation/meta/pull/155 for reference.

Again, I was unable to confirm the regression test locally with
```
$ CFLAGS=-Ofast tox -re py38 -- -k test_no_fast_math_optimization
```

### CODE REVIEW

**Comment by mgedmin** [comment]
Okay, what is going on here.

AFAIK zope.interface doesn't depend on any other packages containing C code, so pip cache containing a .so linked to the fastmath runtime is unlikely.  Why did only one build job fail?

**Comment by mgedmin** [comment]
I downloaded [zope.interface-Linux-2.7.whl](https://github.com/zopefoundation/zope.interface/suites/8217061208/artifacts/358892071) from the GHA build artifacts, extracted the _zope_interface_coptimizations.so from it, and ran the [fast_check_for_ffast_math.py](https://gist.github.com/moyix/2154125d0cb9947ec0525fb49449fab7) script mentioned in [the blog post](https://moyix.blogspot.com/2022/09/someones-been-messing-with-my-subnormals.html).

It says

> _zope_interface_coptimizations.so (1 constructor) is clean

**Comment by mgedmin** [comment]
I reran the failed job with debug output enabled, and it shows the pip cache containing two wheels:

```
../../../.cache/pip/wheels/1c/d7/2d/aefbee2bf20e0ed968d4ab943e03451db0f14c52b5f624fc7e/docopt-0.6.2-py2.py3-none-any.whl
../../../.cache/pip/wheels/cb/
../../../.cache/pip/wheels/cb/83/
../../../.cache/pip/wheels/cb/83/06/
../../../.cache/pip/wheels/cb/83/06/74322eeb187c9f63b9dc744f423958114a544f6847d2f88bca/
../../../.cache/pip/wheels/cb/83/06/74322eeb187c9f63b9dc744f423958114a544f6847d2f88bca/faulthandler-3.2-cp27-cp27mu-linux_x86_64.whl
```

https://pypi.org/project/faulthandler/#files has no Linux wheels, so it's a local cached build of faulthandler that was previously built with -Ofast, which explains everything.

Will wipe the cache.

```
gh api --method DELETE -H "Accept: application/vnd.github+json" /repos/zopefoundation/zope.interface/actions/caches?key=Linux-pip-2.7
```

**Comment by mgedmin** [comment]
> AFAIK zope.interface doesn't depend on any other packages containing C code, so pip cache containing a .so linked to the fastmath runtime is unlikely. Why did only one build job fail?

To summarize: I was wrong.  zope.interface GHA builds depend on faulthandler, which is part of the stdlib, so the pip install (and wheel caching) happen only for Python 2.7, explaining why only the 2.7 build was broken.

**Review by davisagli — APPROVED** [review]
LGTM

**Pull request merged**
