### PR TITLE
3.6 (Untrack self when deallocating. #100)

### PR DESCRIPTION
**Pull request by y-fujisaki2**
https://github.com/zopefoundation/zope.interface/issues/100

To eliminate the error, we have added below program which exclude objects from GC in the destructor in line 4.

static void
Wrapper_dealloc(Wrapper *self)
{
  PyObject_GC_UnTrack((PyObject *)self); //Add this line to eliminate self from GC
  Wrapper_clear(self);
  self->ob_type->tp_free((PyObject*)self);
}

[zope.interface.zip](https://github.com/zopefoundation/zope.interface/files/1301445/zope.interface.zip)

### CODE REVIEW

**Comment by mgedmin** [comment]
It looks like you accidentally created a pull request from the wrong branch.

**Comment by y-fujisaki2** [comment]
Thank you for following.
If you know, could you tell me which branch should I select from belows?
These are 4 branches I can select now.

 - 3.6  : on May 4
 - 3.7  : on Jun 12 2012
 - dont_cache_lookup_failures  : on May 4
 - pure-ci  : on Apr 15 2016

**Comment by mgedmin** [comment]
You have to create a new branch.

For a patch this simple, you can do that online: 
1. Go to https://github.com/zopefoundation/zope.interface/
2. Find the file you want to change: https://github.com/zopefoundation/zope.interface/blob/master/src/zope/interface/_zope_interface_coptimizations.c
3. Click the Edit button on the right
screenshot
4. Make the changes
5. Fill in the commit title and description on the bottom
6. (If given this choice) select "Create a new branch for this commit and start a pull request"
7. Click "Propose file change"
8. (This part I'm typing from memory, so I hope I remember it right!) You get a pre-filled new pull request form which you can submit without changing anything, it should be good.

**Comment by y-fujisaki2** [comment]
Thank you so much for your navigation. I done it.

**Pull request closed without merging**
