### PR TITLE
README.rst: Add PyPI latest version badge

### PR DESCRIPTION
**Pull request by msabramo**
I find it handy to be able to flip back and forth easily between the source code repo and PyPI.

Preview at https://github.com/msabramo/zope.interface/blob/add_pypi_badge/README.rst

### CODE REVIEW

**Comment by mgedmin** [comment]
Thank you.

It's a shame that Travis CI badge no longer uses the original shields.io-style:
ekrano nuotrauka is 2015-01-26 19 21 13

Maybe we should use https://img.shields.io/pypi/v/zope.interface.svg?style=flat to have both badges in the current Travis style (flat)?

pypi travis

Or replace the direct Travis badge with https://img.shields.io/travis/zopefoundation/zope.interface.svg to have both badges in the traditional shields-io style?

pypi travis

Preferences?  Anyone?

**Comment by mgedmin** [comment]
Actually pyp.ip also supports `?style=flat`, and looks better than the shields.io/pypi badge (I don't like the `v` prefix or the multitude of colours.)

pypi travis

Can you please amend your PR to include `?style=flat`?

**Comment by tseaver** [comment]
I agree with @mgedmin -- the flat style looks better.

**Comment by msabramo** [comment]
Changed it to the flat style and I also agree that it looks better.

**Comment by mgedmin** [comment]
:sparkles: Thank you! :sparkles:

**Pull request merged**
